namespace Euler
{
    using System;

    public class Problem2 : IProblems
    {
        public void Pose()
        {
            string q = @"
PROBLEM 2:
Each new term in the Fibonacci sequence is generated by adding the previous two terms.
By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
";
            Console.WriteLine(q);
        }

        public string Solve()
        {
            Console.WriteLine("Here is the solution:");
            int n = 3;
            int maxValue = 1000;

            // Initialise Fibonacci sequence
            int a = 1;
            int b = 2;
            int sum = 2;
            int tmp = 0;
            while (a <= maxValue)
            {
                tmp = b;
                b = a + tmp;
                a = tmp;
                if ((b % n) == 0)
                {
                    sum = sum + b;
                }
            }

            return sum.ToString();
        }
    }
}
